// src/app/layout.tsx
import './globals.css'; // Assuming your global styles are here
import Providers from './providers'; // Or the correct path to your providers file
import Navbar from '@/components/layout/Navbar'; // Added Navbar import
import Footer from '@/components/layout/Footer'; // Added Footer import

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <Navbar /> {/* Added Navbar component */}
          <main className="flex-grow">
            <Providers>{children}</Providers>
          </main>
          <Footer /> {/* Added Footer component */}
        </div>
      </body>
    </html>
  );
}
