// src/app/layout.tsx
import './globals.css'; // Assuming your global styles are here
import Providers from './providers'; // Or the correct path to your providers file

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
